# Generated by Django 3.2.16 on 2023-02-18 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_data',
            name='lead',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_data',
            name='mobile',
            field=models.CharField(default=0, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_data',
            name='notes',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking_data',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'declined')], default=0),
        ),
    ]
